### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by leepafc2** [rdephillip/CNX_FiveM_RP#81]
Hi I just want to say well done on sharing the files to the public, I am wondering if I can use this for our server called StateWideRP? If so please can you reply. You can also add me on discord measlystorm#2274
thank you.

**Comment by rdephillip** [comment]
@leepafc2 This is our resource folder collection of all the mods we hand picked from the FiveM community forums!  They are customized for our server at this time so you'd have to go through the permissions for vMenu and the whitelisting for vBasic and build the Server.CFG yourself.  You will also have to customize the Tablet code to point to your own CAD. Please don't have your members trying to access our CAD as it will not sustain a heavy load of users.

Otherwise as they are simply a collective of public domain mods... have at it friend :D

Vespura's discord is very helpful if you need assistance with vMenu or vBasic.  The others will receive support from the FiveM Community forums.

Note that RP Toolbox isn't released any longer.  They pulled it.  You may want to search for an alternative to this.

Our devs on our server will be developing a custom mod soon to eliminate everything outside of vMenu and to hook into a custom CAD we are building.  At this time we compliment our setup with Open CAD.
