### ISSUE TITLE
no issue just a question 

### ISSUE THREAD

**Issue by markbucko12341** [rdephillip/CNX_FiveM_RP#82]
is there away to set this so just police can use the /cuff  as I have installed it and other player are cuffing people

**Comment by rdephillip** [comment]
RP Toolbox has configurations and LEO options are only supposed to work with LEO Skins, but that mod has proven to be buggy and unreliable.  We actually implemented something else, but we'll be creating customized menus with this lockout.

This is a temporary build out using public tools that we do not write or maintain.  We simply use GitHub as a means of connecting our developers at this time.  Our custom development is done in a private location.

I'd send you to RP Toolbox for support, but the developer is throwing a tantrum because his code is being forked even though FiveM clearly states you cannot "own" your mods in FiveM that you create.
